server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
spring:
  boot:
    admin:
      client:
        url:
        - http://host.docker.internal:1111/